### ISSUE TITLE
clone 项目报错 :(

### ISSUE THREAD

**Issue by AlanJun** [Tencent/deepx_core#1]
Error downloading object: doc/pic/graph_arch.png (1491500): Smudge error: Error downloading doc/pic/graph_arch.png (1491500962c42d9ce9d5a8b4c61256a577d414dbb796108f64d29b534a0ffc2c): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by yuanms2** [comment]
I have the same issue.

**Comment by zhangyafeikimi** [comment]
Sorry for that. Tencent's lfs bandwidth quota is exhausted. My colleagues are trying to fix the issue.

**Comment by zhangyafeikimi** [comment]
Maybe forking it can fix it temporarily.

**Comment by zhangyafeikimi** [comment]
I deleted all lfs files, and add them back to regular storage.
Try it again.

**Comment by zhangyafeikimi** [comment]
The mirror is always available:
https://git.code.tencent.com/Tencent_Open_Source/deepx_core

**Comment by AlanJun** [comment]
cool, I've successfully clone the project
