### ISSUE TITLE
小而美之外，设计上有哪些考虑？

### ISSUE THREAD

**Issue by stonehuang1024** [Tencent/deepx_core#3]
编译运行的demo并大概浏览了代码，确实是小而美，很不错！ 也想请教下亚霏大神在设计deepx_core的一些考虑点

优点
1.小而美，针对推搜广大规模稀疏场景而设计，离散特征、ps、线上server都有解决方案
2.依赖少，编译部署简单，除了libhdfs.so外，一键编译和运行，demo可以很快跑起来
3.基于静态图，可以自定义网络，相比abcus通用性更好
4.代码简洁，没有明显冗余设计

疑问：
1.序列化和反序列化需要自定义代码，是否会考虑用pb
2.目前不支持GPU，未来是否考虑支持
3.计算方面没有采用矩阵库如eigen，性能是否有影响
4.op略复杂（代码量较大），是否有更好的抽象

**Comment by zhangyafeikimi** [comment]
libhdfs.so的考虑也可以探讨一下.

微信内部的环境, 有hadoop 2.2.0和2.6.0, 这两个版本的libhdfs.so是不同的, 不能混用. 所以把libhdfs以静态库的方式链接进去不是一个很好的方案.

libhdfs.so的使用是dlopen的方式, 也不是链接进去的. 相当于是, 有so则hdfs可用, so的版本是什么都可以. 保持了相当的灵活性.

**Comment by stonehuang1024** [comment]
感谢亚霏大神的回答.
1.op相比tf粒度比较粗，很多op是可以通过细粒度的op组装起来的，是想了解这方面的考虑点
2.关于异构计算方面，目前测试GPU在serving（ONNX）上有比较大的收益，方便透露下deep_core后续异构计算会考虑哪些方向？
3.编译工具是否会考虑用blade（广点通开源的工具）
4.特征sign设计方面，前16位分配给slot，是否会有些浪费？导致hash部分冲突率比较高，目前推搜广特征动不动就千亿
5.还想探讨下，deep_core设计灵感（血统）的来源，Caffe、tf、mxnet、abcus感觉都不太像，更接近于angel？

**Comment by stonehuang1024** [comment]
感谢亚霏大神的回答，也想继续探讨下
1.op相比tf粒度比较粗，很多op是可以通过细粒度的op组装起来的，是想了解这方面的考虑点
2.关于异构计算方面，目前测试GPU在serving（ONNX）上有比较大的收益，方便透露下deep_core后续异构计算会考虑哪些方向？
3.编译工具是否会考虑用blade（广点通开源的工具）
4.特征sign设计方面，前16位分配给slot，是否会有些浪费？导致hash部分冲突率比较高，目前推搜广特征动不动就千亿
5.还想探讨下，deep_core设计灵感（血统）的来源，Caffe、tf、mxnet、abcus感觉都不太像，更接近于angel？

**Comment by zhangyafeikimi** [comment]
op有粗粒度也有细粒度的, 各有优缺点, 粗的倾向于把多个常用操作融合到一起, 节省框架的开销, 细更有灵活性, 可以随意搭积木.

**Comment by zhangyafeikimi** [comment]
没有计划做异构计算

**Comment by zhangyafeikimi** [comment]
https://github.com/Tencent/deepx_core/tree/master/mmsearchgateway
是为bazel写的编译文件, 移植到blade很容易.

**Comment by zhangyafeikimi** [comment]
2的48次方是562949953421312, 千亿几乎无冲突的.

**Comment by zhangyafeikimi** [comment]
参考过tensorflow和mxnet, 别的框架没看过.

**Comment by stonehuang1024** [comment]
get~  感谢大神的回答
