### ISSUE TITLE
doc下面所有的图片都挂掉了

### ISSUE THREAD

**Issue by AlanJun** [Tencent/deepx_core#4]
doc下面所有的图片都挂掉了，很多用于示意的框架图不可看

**Comment by zhangyafeikimi** [comment]
问题是Tencent企业账号的lfs空间不够了, 相关的同事在想办法.

**Comment by zhangyafeikimi** [comment]
试试能不能fork出来一份, 然后能不能看到?

**Comment by zhangyafeikimi** [comment]
可能是国内的被墙了, 我这里也看不到.

https://git.code.tencent.com/Tencent_Open_Source/deepx_core

**Comment by AlanJun** [comment]
cool, it works
